//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriApp.Resources.Strings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AnthropometricEvaluationStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnthropometricEvaluationStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NutriApp.Resources.Strings.AnthropometricEvaluationStrings", typeof(AnthropometricEvaluationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string SevenPleatsJacksonPolloc {
            get {
                return ResourceManager.GetString("SevenPleatsJacksonPolloc", resourceCulture);
            }
        }
        
        internal static string ThreePleatsJacksonPolloc {
            get {
                return ResourceManager.GetString("ThreePleatsJacksonPolloc", resourceCulture);
            }
        }
        
        internal static string FourPleatsDurninWomersley {
            get {
                return ResourceManager.GetString("FourPleatsDurninWomersley", resourceCulture);
            }
        }
        
        internal static string ThreePleatsGuedes {
            get {
                return ResourceManager.GetString("ThreePleatsGuedes", resourceCulture);
            }
        }
        
        internal static string FourPleatsPetroski {
            get {
                return ResourceManager.GetString("FourPleatsPetroski", resourceCulture);
            }
        }
    }
}
