//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriApp.Resources.Strings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EvaluationMenuStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EvaluationMenuStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NutriApp.Resources.Strings.EvaluationMenuStrings", typeof(EvaluationMenuStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Imc {
            get {
                return ResourceManager.GetString("Imc", resourceCulture);
            }
        }
        
        internal static string PesoIdeal {
            get {
                return ResourceManager.GetString("PesoIdeal", resourceCulture);
            }
        }
        
        internal static string PesoAjustado {
            get {
                return ResourceManager.GetString("PesoAjustado", resourceCulture);
            }
        }
        
        internal static string AdequacaoPeso {
            get {
                return ResourceManager.GetString("AdequacaoPeso", resourceCulture);
            }
        }
        
        internal static string AlturaEstimada {
            get {
                return ResourceManager.GetString("AlturaEstimada", resourceCulture);
            }
        }
        
        internal static string Circunferias {
            get {
                return ResourceManager.GetString("Circunferias", resourceCulture);
            }
        }
        
        internal static string SemiologiaNutricional {
            get {
                return ResourceManager.GetString("SemiologiaNutricional", resourceCulture);
            }
        }
        
        internal static string CircunferenciaCintura {
            get {
                return ResourceManager.GetString("CircunferenciaCintura", resourceCulture);
            }
        }
        
        internal static string CircunferenciaPanturrilha {
            get {
                return ResourceManager.GetString("CircunferenciaPanturrilha", resourceCulture);
            }
        }
        
        internal static string ValorReference {
            get {
                return ResourceManager.GetString("ValorReference", resourceCulture);
            }
        }
        
        internal static string AnthropometricEvaluation {
            get {
                return ResourceManager.GetString("AnthropometricEvaluation", resourceCulture);
            }
        }
        
        internal static string ComposicaoCorporal {
            get {
                return ResourceManager.GetString("ComposicaoCorporal", resourceCulture);
            }
        }
        
        internal static string PesoEstimado {
            get {
                return ResourceManager.GetString("PesoEstimado", resourceCulture);
            }
        }
    }
}
